# Autograd with tensors

In [ ]:
# Autograd automatically calculates gradients for tensors. Works by keeping track of operations performed on tensors, then goes back to calculate tensors

In [1]:
import torch

In [2]:
w = torch.randn(4,3,requires_grad=True)

In [3]:
w

tensor([[-0.1716, -0.1296, -0.5612],
        [ 1.2359, -1.2045,  0.4344],
        [ 1.4254, -0.6043, -0.5008],
        [ 0.4314, -0.8913,  1.0994]], requires_grad=True)

In [4]:
# turn off
w.requires_grad_(False)
w

tensor([[-0.1716, -0.1296, -0.5612],
        [ 1.2359, -1.2045,  0.4344],
        [ 1.4254, -0.6043, -0.5008],
        [ 0.4314, -0.8913,  1.0994]])

In [5]:
# turn back on

w.requires_grad_(True)
w

tensor([[-0.1716, -0.1296, -0.5612],
        [ 1.2359, -1.2045,  0.4344],
        [ 1.4254, -0.6043, -0.5008],
        [ 0.4314, -0.8913,  1.0994]], requires_grad=True)

In [6]:
# create new tensor

y = torch.exp(w)
print(y)

tensor([[0.8423, 0.8785, 0.5705],
        [3.4416, 0.2998, 1.5441],
        [4.1594, 0.5465, 0.6060],
        [1.5395, 0.4101, 3.0023]], grad_fn=<ExpBackward>)


In [7]:
print(y.grad_fn)

In [8]:
outp = y.mean()
print(outp)

tensor(1.4867, grad_fn=<MeanBackward0>)


In [9]:
print(w.grad)

# haven't run backward function yet, so None

None


In [11]:
outp.backward()

# calcualtes outp with respect to w

RuntimeError: ignored

In [12]:
print(w.grad)

tensor([[0.0702, 0.0732, 0.0475],
        [0.2868, 0.0250, 0.1287],
        [0.3466, 0.0455, 0.0505],
        [0.1283, 0.0342, 0.2502]])


In [13]:
# detach from computation history (prevent tracking history)

print(w.detach())

tensor([[-0.1716, -0.1296, -0.5612],
        [ 1.2359, -1.2045,  0.4344],
        [ 1.4254, -0.6043, -0.5008],
        [ 0.4314, -0.8913,  1.0994]])


In [14]:
print(outp.requires_grad)

True


In [16]:
print(outp.requires_grad)
with torch.no_grad():
  outp = (w+y).mean()

print(outp.requires_grad) 

True
False
