# Tensors 

In [1]:
import torch

## zeros()

In [2]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [3]:
w.size()

torch.Size([4, 3])

In [4]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [6]:
w = torch.randn(4,3)
w

tensor([[ 0.7812,  1.6222,  2.1169],
        [-0.7784,  0.9490,  1.1651],
        [-1.0375,  1.1816, -0.7023],
        [ 0.8569, -0.8133, -0.7448]])

In [7]:
t = torch.randn_like(w)
t

tensor([[ 1.4357,  1.0982,  0.8536],
        [ 0.9368,  0.7021,  1.0126],
        [ 1.1245, -0.1329,  0.1916],
        [-1.2613, -0.3744, -0.2403]])

## fill_()

In [8]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [10]:
#reshape tensor

t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [12]:
# convert from torch tensor to numpy array

w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [13]:
type(w.numpy())

numpy.ndarray